env:
  X: Y

# container:
#   image: rust:latest

test_task:
  container:
    matrix:
      - image: rust:latest
      - image: rustlang/rust:nightly
  build_script:
    - apt update && apt install -y cmake git
    - cargo build
  test_script: cargo test
