env:
  X: Y

container:
  image: rust:latest

test_task:
  # container:
  #   matrix:
  #     - image: teeks99/gcc-ubuntu:latest
  #     - image: teeks99/clang-ubuntu:latest
  build_script:
    - apt update && apt install -y cmake git
    - cargo build
  test_script: cargo test