env: X=Y
  - ARCH=x86_64
  - ARCH=i686

compiler: rustc

language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - linux


#install: make ninja cmake get-deps
#before_install:

addons:
  apt:
    packages:
      - gcc-multilib

# script: skip

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    # - script: 'cargo build --verbose --workspace'
    - script: 'cargo build --verbose'
    - script: 'cargo test --verbose'
